### ISSUE TITLE
attempt to index local 'lua_entity' (a nil value)

### ISSUE THREAD

**Issue by do0dleme** [fluxionary/minetest-replacer_redo#13]
`2022-11-29 16:33:52: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'inspector' in callback item_OnUse(): ...ds/world/worldmods/replacer_redo/inspector/inspector.lua:46: attempt to index local 'lua_entity' (a nil value)`
`2022-11-29 16:33:52: ERROR[Main]: stack traceback:`
`2022-11-29 16:33:52: ERROR[Main]: 	...ds/world/worldmods/replacer_redo/inspector/inspector.lua:46: in function <...ds/world/worldmods/replacer_redo/inspector/inspector.lua:13>`

**Comment by fluxionary** [comment]
@do0dleme it's easy to fix that crash, but out of curiousity, what did you click on to get that error? 

also it might be a day or two until i push the fix, i'm currently working on a unification of the boilerplate of all my mods, and it needs some more testing.

**Comment by fluxionary** [comment]
@do0dleme this should be fixed in the latest update, though i don't know how to re-create it, so i can't really test it.

**Comment by do0dleme** [comment]
steps to get this bug:

1. drop item
2. inspect item
3. take it and change with 2 or 3 more items
4. repeat again but in a fast manner

anyway this did solve the bug so thank you :)

**Comment by fluxionary** [comment]
oh, i think i see what happened. the item was unloaded by the time the callback actually got called. good to know that can happen.
