### ISSUE TITLE
attempt to call local 'func' (a table value)

### ISSUE THREAD

**Issue by do0dleme** [fluxionary/minetest-replacer_redo#14]
crash after trying to replace `default:dirt_with_snow` with `wool:red`

`2022-11-30 23:18:02: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod '' in callback item_OnUse(): ...orld/worldmods/minetest-futil/minetest/serialization.lua:27: attempt to call local 'func' (a table value)`
`2022-11-30 23:18:02: ERROR[Main]: stack traceback:`
`2022-11-30 23:18:02: ERROR[Main]: 	...orld/worldmods/minetest-futil/minetest/serialization.lua:27: in function 'deserialize'`
`2022-11-30 23:18:02: ERROR[Main]: 	...orld/worldmods/minetest-futil/minetest/serialization.lua:87: in function 'deserialize_node_meta'`
`2022-11-30 23:18:02: ERROR[Main]: 	...dmods/minetest-replacer_redo/replacer/api/creaplacer.lua:208: in function <...dmods/minetest-replacer_redo/replacer/api/creaplacer.lua:108>`

**Comment by fluxionary** [comment]
actually, this is a bug w/ futil. it should be fixed now.

**Comment by do0dleme** [comment]
oh my bad. thank you nonetheless!
